apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "another-test-githubapp"
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "gitHubApp"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "credentials from Kubernetes"
type: Opaque
stringData:
  appID: 1234
  privateKey: |-
    -----BEGIN PRIVATE KEY-----
    ...
    -----END PRIVATE KEY-----
